server:
  port: 10010

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka

spring:
  application:
    name: gateway

# 路由规则
zuul:
  routes:
    # 默认都配置 user-service: /user-service/**
    user-service:
      path: /user/**
      serviceId: user-service
        # 让前缀不忽略 即不需要传入 /user/user/4 而是 /user/4
        strip-prefix: false
  # 默认不配置的
  ignored-services:
    - consumer-service
  # 全局前缀
  prefix: /fix
  # 全局让前缀不忽略 即不需要传入 /user/user/4 而是 /user/4
  strip-prefix: true

