server:
  port: 8081
  servlet:
    path: /
logging:
  level:
    cn.imust.user: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
mybatis:
  type-aliases-package: cn.imust.user.pojo