server:
  port: 8083
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1

# feign 开启熔断
feign:
  hystrix:
    enabled: true

## 配置hystrix全局超时时间
#hystrix:
#  command:
#    # 针对全局
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
#    # 针对user-service 也可以写方法
#    user-service:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000